name: Build ICU and i18n on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Visual Studio
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

    - name: Install Ninja (Optional for faster builds)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Download ICU source
      run: |
        curl -LO https://github.com/unicode-org/icu/releases/download/release-73-1/icu4c-73_1-src.zip
        unzip icu4c-73_1-src.zip
        move icu icu4c-src

    - name: Set up ICU environment
      run: |
        cd icu4c-src/source
        set PATH=%PATH%;C:\Program Files\CMake\bin
        set ICUPROJ=msvc

    - name: Build ICU Libraries
      run: |
        cd icu4c-src/source
        nmake /f Makefile.msc

    - name: Install ICU Libraries
      run: |
        cd icu4c-src/source
        nmake /f Makefile.msc install

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: icu-build
        path: icu4c-src/source/bin
